apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: processing-scaler
  labels:
    app: processing-service
    assignment-id: {{ .Values.assignmentId | quote }}
spec:
  scaleTargetRef:
    name: processing-service 
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
  - type: redis-streams
    metadata:
      address: redis-service:{{ .Values.redis.service.port }}
      stream: {{ .Values.autoscaling.stream }}
      consumerGroup: {{ .Values.autoscaling.group }}
      pendingEntriesCount: {{ .Values.autoscaling.threshold | quote }}